version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    when:
        or:
          - equal: [ staging, << pipeline.git.branch >> ]
    jobs:
      - heroku/deploy-via-git    
