workflows:
  version 2:
  heroku_deploy:
    jobs:
      parameters:
        api-key:
          default: HEROKU_API_KEY
          type: env_var_name
        app-name:
          default: $HEROKU_APP_NAME
          type: string
        branch:
          default: $CIRCLE_BRANCH
          type: string
        force:
          default: false
          type: boolean
        maintenance-mode:
          default: false
          type: boolean
        no_output_timeout:
          default: 10m
          type: string
        tag:
          default: $CIRCLE_TAG
          type: string
      steps:
        - when:
            condition: << parameters.maintenance-mode >>
            steps:
              - run:
                  command: 'heroku maintenance:on --app << parameters.app-name >>'
                  name: Turn ON maintenance mode.
        - run:
            command: >
              if << parameters.force >>;then
                force="-f"
              fi


              heroku_url="https://heroku:$<< parameters.api-key>>@git.heroku.com/<<parameters.app-name >>.git"


              if [ -n "<< parameters.branch >>" ]; then
                git push $force $heroku_url << parameters.branch >>:staging
              elif [ -n "<< parameters.tag >>" ]; then
                  git push $force $heroku_url << parameters.tag >>^{}:staging
              else
                echo "No branch or tag found."
                exit 1
              fi
            name: Deploy branch or tag to Heroku via git push
            no_output_timeout: << parameters.no_output_timeout >>
        - when:
            condition: << parameters.maintenance-mode >>
            steps:
              - run:
                  command: 'heroku maintenance:off --app << parameters.app-name >>'
                  name: Turn OFF maintenance mode.
