version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: Staging
      - heroku/deploy-via-git
