version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  deploy:
    - run:
        command:|
           if [ "${CIRCLE_BRANCH}" != "Melvin" ];
            then
              exit
            fi
    - heroku/deploy-via-git
    
