version: 2.1
jobs:
  deploy_melvin:
    docker:
      - image: cimg/base:stable
    parameters:
      api-key:
        default: $HEROKU_API_KEY
        type: string
    steps:
      - checkout
      - run:
         command: |
           heroku_url="https://heroku:<< parameters.api-key >>@git.heroku.com/circleci-hero.git"
             git push  $heroku_url HEAD:master --force
workflows:
  version: 2.1
  heroku_deploy_melvin:
    jobs:
      - deploy_melvin:
          filters:
            branches:
              only: 
                - Staging
