version: 2.1
jobs:
  deploy_to_heroku:
    docker:
      - image: cimg/base:stable
    parameters:
      api-key:
        default: $HEROKU_API_KEY
        type: string
    steps:
      - checkout
      - run:
         command: |
           git add .
             git commit -m "My first commit"
               heroku_url="https://heroku:<< parameters.api-key >>@git.heroku.com/circleci-hero.git"
                 git push $force $heroku_url master
workflows:
  version: 2.1
  heroku_deploy:
    jobs:
      - deploy_to_heroku
